install_os_packages: true
oracle_stage: /u01/stage
oracle_rsp_stage: "{{ oracle_stage }}/rsp"

oracle_user: oracle                        # User that will own the Oracle Installations.
oracle_group: oinstall                          # Primary group for oracle_user.

# selinux
disable_selinux: true

oracle_groups:
  - { group: oinstall, gid: 54321 }
  - { group: dba, gid: 54322 }
  - { group: backupdba, gid: 54323 }
  - { group: oper, gid: 54324 }
  - { group: dgdba, gid: 54325 }
  - { group: kmdba, gid: 54326 }

oracle_users:         # Passwd :Oracle123
  - { username: oracle, uid: 54321, primgroup: oinstall, othergroups: "dba,backupdba,dgdba,kmdba,oper", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }
 
oracle_packages:
  - binutils
  - compat-libcap1
  - compat-libstdc++-33
  - glibc
  - glibc-devel
  - ksh
  - libaio
  - libaio-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libxcb
  - libX11
  - libXau
  - libXi
  - libXtst
  - make
  - net-tools
  - nfs-utils
  - smartmontools
  - sysstat
  - gcc-c++

oracle_sysctl:
  - { name: kernel.shmall, value: 4294967296 }
  - { name: kernel.shmmax, value: 68719476736 }
  - { name: kernel.shmmni, value: 4096 }
  - { name: kernel.sem, value: "250 32000 100 128" }
  - { name: fs.file-max, value: 6815744 }
  - { name: fs.aio-max-nr, value: 3145728 }
  - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
  - { name: net.core.rmem_default, value: 262144 }
  - { name: net.core.rmem_max, value: 4194304 }
  - { name: net.core.wmem_default, value: 262144 }
  - { name: net.core.wmem_max, value: 1048576 }
  - { name: kernel.panic_on_oops, value: 1 }

oracle_seclimits:
  - { name: 'soft nproc', value: 16384 }
  - { name: 'hard nproc', value: 16384 }
  - { name: 'soft nofile', value: 4096 }
  - { name: 'hard nofile', value: 65536 }
  - { name: 'soft stack', value: 10240 }
  - { name: 'hard stack', value: 32768 }
  - { name: 'soft memlock', value: "{{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}" }
  - { name: 'hard memlock', value: "{{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}" }
