---

- include: listener.yml
  tags: listener

- name: Check if database is already created
  shell: grep {{ oracle_sid }}:{{ oracle_home_db }} /etc/oratab
  # when: oracle_db_name is defined
  ignore_errors: yes
  tags: checkifdbexists
  register: checkdbexist

- name: Create responsefile for dbca
  template: src=dbca-create-db.{{oracle_version_db}}.rsp.j2 dest={{ oracle_rsp_stage }}/dbca-create-db.{{oracle_version_db}}.rsp owner={{ oracle_user }} group={{ oracle_group }} mode=644 backup=no
  when: checkdbexist.rc == 1
  tags:
  - dbcaresponse

- name: Create database
  shell: "{{ oracle_home_db }}/bin/dbca -createDatabase -silent -responseFile {{ oracle_rsp_stage }}/dbca-create-db.{{oracle_version_db}}.rsp"
  become: yes
  become_user: "{{ oracle_user }}"
  tags:
    - oradbcreate
  when: checkdbexist.rc == 1
  register: oradbcreate

- debug: var=item
  loop: "{{ oradbcreate.stdout|map(attribute='stdout_lines')|list }}"
  tags:
    - oradbcreate
  when: oradbcreate.changed
  ignore_errors: true

- name: Check if database is running
  shell: ps -ef | grep pmon | grep -v grep
  tags:
    - psout
  register: psout
  ignore_errors: true

- debug: var=psout.stdout_lines
  tags:
    - psout
