---
oracle_packages:
  - binutils
  - compat-libcap1
  - compat-libstdc++-33
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - ksh
  - libaio
  - libaio-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libXi
  - libXtst
  - make
  - sysstat
  - unixODBC
  - unixODBC-devel

## oracle softwares
# oracle_software_11201:
#   - linux.x64_11gR2_database_1of2.zip
#   - linux.x64_11gR2_database_2of2.zip
# oracle_software_11204:
#   - p13390677_112040_Linux-x86-64_1of7.zip
#   - p13390677_112040_Linux-x86-64_2of7.zip
#   - p13390677_112040_Linux-x86-64_3of7.zip

oracle_groups:
  - { group: oinstall, gid: 54321 }
  - { group: dba, gid: 54322 }
  - { group: backupdba, gid: 54323 }
  - { group: oper, gid: 54324 }
  - { group: dgdba, gid: 54325 }
  - { group: kmdba, gid: 54326 }

oracle_sysctl:
  - { name: kernel.semmsl, value: 250 }
  - { name: kernel.semmns, value: 32000 }
  - { name: kernel.semopm, value: 100 }
  - { name: kernel.semmni, value: 128 }
  - { name: kernel.shmall, value: 2097152 }
  - { name: kernel.shmmax, value: 4294967295 }
  - { name: kernel.shmmni, value: 4096 }
  - { name: kernel.sem, value: "250 32000 100 128" }
  - { name: fs.file-max, value: 6815744 }
  - { name: fs.aio-max-nr, value: 1048576 }
  - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
  - { name: net.core.rmem_default, value: 262144 }
  - { name: net.core.rmem_max, value: 4194304 }
  - { name: net.core.wmem_default, value: 262144 }
  - { name: net.core.wmem_max, value: 1048576 }

oracle_seclimits:
  - { name: 'soft nproc', value: 2047 }
  - { name: 'hard nproc', value: 16384 }
  - { name: 'soft nofile', value: 1024 }
  - { name: 'hard nofile', value: 65536 }
  - { name: 'soft stack', value: 10240 }
  - { name: 'hard stack', value: 32768 }

oracle_users:         # Passwd :Oracle123
  - { username: oracle, uid: 54321, primgroup: oinstall, othergroups: "dba,backupdba,dgdba,kmdba,oper", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }
 