---

- name: Install packages required by Oracle on OL/RHEL
  yum: name={{ item }} state=installed
  with_items: "{{oracle_packages}}"
  when: install_os_packages 
  tags: os_packages, oscheck

- include: "Redhat-{{ ansible_distribution_major_version }}.yml"

- name: Disable selinux (permanently)
  selinux: 
    state: disabled
  when: disable_selinux
  tags: selinux

- name: Disable selinux (runtime)
  shell: setenforce 0
  when: disable_selinux
  tags: selinux
  ignore_errors: true

- name: Check dns for host
  command: nslookup {{ ansible_hostname }}
  register: ns
  ignore_errors: false
  tags: etchosts

- name: User | Add group(s)
  group: name={{ item.group }} gid={{ item.gid }} state=present
  with_items: "{{oracle_groups}}"
  tags:
    - group

- name: User | Add Oracle user
  user: name={{ item.username }} group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }} generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
  with_items: "{{oracle_users}}"
  tags:
    - user

- name: Oracle-recommended kernel settings
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present 
    reload: yes 
    ignoreerrors: yes
  with_items: "{{ oracle_sysctl }}"
  tags: sysctl

- name: Oracle-recommended security limits
  template: src=oracle-seclimits.conf.j2 dest=/etc/security/limits.conf backup=yes
  tags: seclimit