---

- name: Check for correct OS family & min version
  assert:
    that: 
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version >= 6
    msg: "your linux version:{{ansible_os_family}} <> Redhat or {{ ansible_distribution_major_version }} < 6"
  tags:
    - oscheck

- name: Install common packages OL/RHEL
  when: 
    - install_os_packages 
  with_items: "{{ common_packages }}"
  yum: name={{ item }} state=installed
  tags:
    - commonpackages

- include: "Redhat-{{ ansible_distribution_major_version }}.yml"